# Generated by Django 4.1.5 on 2023-01-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.IntegerField(verbose_name='Внешний ID кабинета')),
                ('ext_name', models.CharField(max_length=100, verbose_name='Внешнее название кабинета')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('cabinets', models.TextField()),
                ('campaigns', models.TextField()),
                ('metrics', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.IntegerField(verbose_name='Внешний ID кампании')),
                ('ext_name', models.CharField(max_length=100, verbose_name='Внешнее название кампании')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='reports.cabinet', verbose_name='Кабинет принадлежности')),
            ],
        ),
    ]
