# Generated by Django 4.1.5 on 2023-04-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000, null=True)),
                ('token', models.CharField(max_length=1000, null=True)),
                ('response', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
