# Generated by Django 4.1.5 on 2023-07-11 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "reports",
            "0004_adplan_statistics_remove_campaign_cabinet_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adplan",
            unique_together={("id", "ad_plan_id", "user")},
        ),
    ]
