# Generated by Django 4.1.5 on 2023-07-11 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0005_alter_adplan_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="statistics",
            unique_together={("id", "ad_plan", "date")},
        ),
    ]
