# Generated by Django 4.1.5 on 2023-08-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_adplan_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='url',
            field=models.FilePathField(path='/Users/s2300101/Code/simplereports/simplereports/reports'),
        ),
    ]
