# Generated by Django 4.1.5 on 2023-10-24 14:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reports",
            "0011_report_ad_plans_report_end_date_report_start_date",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="metrics",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=20, verbose_name="Метрики"
                ),
                choices=[
                    ("shows", "Показы"),
                    ("clicks", "Клики"),
                    ("spent", "Расходы"),
                    ("goals", "Целевые показатели"),
                    ("cpm", "CPM"),
                    ("cpc", "CPC"),
                    ("ctr", "CTR"),
                ],
                null=True,
                size=None,
            ),
        ),
    ]
