# Generated by Django 4.1.5 on 2023-10-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0012_report_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="spent",
            field=models.FloatField(verbose_name="Расходы"),
        ),
    ]
