# Generated by Django 4.1.5 on 2023-10-24 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0013_alter_statistics_spent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="metrics",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=20, verbose_name="Метрики"
                ),
                null=True,
                size=None,
            ),
        ),
    ]
