version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: jinglemybells/simplerep:latest
    restart: always
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  react-app:
    container_name: my_react_app
    image: kapshtykas/simplereports_front
    volumes:
      - .:/react_app
      - app-volume:/app/build/
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - app-volume:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/usr/share/nginx/html/static_backend/
      - media_value:/usr/share/nginx/html/

    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  postgres:
  app-volume:

