# Generated by Django 4.1.5 on 2023-07-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vk_client_token',
            field=models.CharField(max_length=255, null=True, verbose_name='Токен доступа к API ВК'),
        ),
    ]
