# Generated by Django 4.1.5 on 2023-08-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_vk_client_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vk_client_secret',
            field=models.CharField(max_length=1000, null=True, verbose_name='Client secret ВК'),
        ),
    ]
